apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-audios
  labels:
      type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Audios"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-soundwaves
  labels:
      type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Soundwaves"