apiVersion: apps/v1
kind: Deployment
metadata:
  name: featextraction
  labels:
    app: featextraction
  namespace: mer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: featextraction
  template:
    metadata:
      labels:
        app: featextraction
    spec:
      containers:
      - name: featextraction
        image: merteam/featextraction:latest
        imagePullPolicy: Always #no cache
        env:
        - name: HOST
          value: "rabbit"
        - name: USER
          value: "merUser"
        - name: PASS
          value: "passwordMER"
        - name: PORT
          value: "5672"
        - name: MNG_PORT
          value: "15672"
        - name: TIME
          value: "10"
        volumeMounts:
          - mountPath: /Audios
            name: featextraction-pv-storage

      volumes:
        - name: featextraction-pv-storage
          persistentVolumeClaim:
            claimName: pvc-audios
  