apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mer
  labels:
    service: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    nodePort: 30090
    port: 80
    name: frontend