apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mer
  labels:
    service: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    nodePort: 30090
    port: 3000
    name: frontend