apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
  namespace: mer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: merteam/frontend:dev # dev
        # image: merteam/frontend:prod # prod
        imagePullPolicy: Always # no cache
        ports:
        - containerPort: 3000 #dev
        # - containerPort: 80 #prod
          name: frontend
          protocol: TCP

        volumeMounts:
          - mountPath: /Soundwaves
            name: wave2image-pv-storage

      volumes:
        - name: wave2image-pv-storage
          persistentVolumeClaim:
            claimName: pvc-soundwaves