apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicclass-deployment
  labels:
    app: musicclass
  namespace: mer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicclass
  template:
    metadata:
      labels:
        app: musicclass
    spec:
      containers:
      - name: musicclass
        image: merteam/musicclass:latest
        env:
        - name: HOST
          value: "rabbit"
        - name: USER
          value: "merUser"
        - name: PASS
          value: "passwordMER"
        - name: PORT
          value: "5672"
        - name: MNG_PORT
          value: "15672"
        - name: TIME
          value: "10"