apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  labels:
    app: rabbit
  namespace: mer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: merUser
        - name: RABBITMQ_DEFAULT_PASS
          value: passwordMER
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        ports:
          - containerPort: 15672
            name: management
            protocol: TCP
          - containerPort: 5672
            name: rabbit
            protocol: TCP