apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidextractor-deployment
  labels:
    app: vidextractor
  namespace: mer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vidextractor
  template:
    metadata:
      labels:
        app: vidextractor
    spec:
      containers:
      - name: vidextractor
        image: merteam/vidextractor:latest
        env:
        - name: HOST
          value: "rabbit"
        - name: USER
          value: "merUser"
        - name: PASS
          value: "passwordMER"
        - name: PORT
          value: "5672"
        - name: MNG_PORT
          value: "15672"
        - name: TIME
          value: "10"
        volumeMounts:
          - mountPath: /vidExtractor/Audios
            name: task-pv-storage

      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim